services:
  python:
    build:
      #dockerfile: ./Dockerfile
      context: .
    environment:
      LOOKUP_ENDPOINT: http://lookup:8000/lookup/
    ports:
      - 8000:8000
      #volumes:
      #  - ${PWD}/app.py:/app/app.py:ro

  nanomq:
    image: emqx/nanomq:latest-slim
    ports:
      - 1883:1883
      - 9001:9001
    volumes:
      - sqlite:/var/lib/nanomq/sqlite
      - ${PWD}/nanomq/nanomq.conf:/usr/local/nanomq/nanomq.conf:ro
      #- ${PWD}/nanomq.conf:/etc/nanomq.conf:ro
      #- ${PWD}/nanomq_acl.conf:/etc/nanomq_acl.conf:ro
      #- ${PWD}/nanomq_pwd.conf:/etc/nanomq_pwd.conf:ro  # sadly, these files need to be unreadable to group+all to be valid - it just says file missing, it's not missing, it has the wrong permissions, the error message sucks

  lookup:
    build:
      context: /Users/allan.callaghan/code/personal/lookupCacheAPI/
    environment:
      - CACHE_TIMEOUT_MINUTES=9999
      - CACHE_PATH=/__cache/lookup.sqlite
    ports:
      - 8002:8000
    volumes:
      - lookup:/__cache/

volumes:
  sqlite:
  lookup:
